<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="7" hostname="P2B-69WFNK2" name="Maven.ActionTest" tests="8" failures="0" timestamp="08 Sep 2018 10:40:21 GMT" time="191.032" errors="1">
  <testcase name="dataExcel" time="191.032" classname="Maven.ActionTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Maven.ActionTest.doLogin(ActionTest.java:134)
	at Maven.ActionTest.dataExcel(ActionTest.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- dataExcel -->
  <testcase name="takescreenshotDemo" classname="Maven.ActionTest">
    <skipped/>
  </testcase> <!-- takescreenshotDemo -->
  <testcase name="demoFileupload" classname="Maven.ActionTest">
    <skipped/>
  </testcase> <!-- demoFileupload -->
  <testcase name="seleniumGrid" classname="Maven.ActionTest">
    <skipped/>
  </testcase> <!-- seleniumGrid -->
  <testcase name="demoRobot" classname="Maven.ActionTest">
    <skipped/>
  </testcase> <!-- demoRobot -->
  <testcase name="javascriptDemo" classname="Maven.ActionTest">
    <skipped/>
  </testcase> <!-- javascriptDemo -->
  <testcase name="cookieDemo" classname="Maven.ActionTest">
    <skipped/>
  </testcase> <!-- cookieDemo -->
  <testcase name="demoTest" classname="Maven.ActionTest">
    <skipped/>
  </testcase> <!-- demoTest -->
</testsuite> <!-- Maven.ActionTest -->
